version: "3.8"

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "10001:6379"
      - "13333:8001"
    volumes:
      - redis-data:/data
      - ./redis-stack.conf:/redis-stack.conf
volumes:
  redis-data:
 
networks:
  default:
    external: 
      name: stack